-- MySQL Script generated by MySQL Workbench
-- Thu Dec  9 17:08:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema colab_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `colab_db` ;

-- -----------------------------------------------------
-- Schema colab_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colab_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `colab_db` ;

-- -----------------------------------------------------
-- Table `colab_db`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`book` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `book_type` VARCHAR(45) NULL DEFAULT NULL,
  `edition` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`course` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `course_subject` VARCHAR(45) NULL DEFAULT NULL,
  `book` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_book` (`book` ASC) VISIBLE,
  CONSTRAINT `course_book`
    FOREIGN KEY (`book`)
    REFERENCES `colab_db`.`book` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`student` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `degree` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`certificate` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `date_issued` DATE NULL DEFAULT NULL,
  `course` INT NULL DEFAULT NULL,
  `student` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cert_student_idx` (`student` ASC) VISIBLE,
  INDEX `cert_course_idx` (`course` ASC) VISIBLE,
  CONSTRAINT `cert_course`
    FOREIGN KEY (`course`)
    REFERENCES `colab_db`.`course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cert_student`
    FOREIGN KEY (`student`)
    REFERENCES `colab_db`.`student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`department` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `size` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`teacher` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `department` INT NULL DEFAULT NULL,
  `num_of_reports` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `teacher_department_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `teacher_department`
    FOREIGN KEY (`department`)
    REFERENCES `colab_db`.`department` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`institution` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`principal` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `institution` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `institution_UNIQUE` (`institution` ASC) VISIBLE,
  INDEX `principal_institution_idx` (`institution` ASC) VISIBLE,
  CONSTRAINT `principal_institution`
    FOREIGN KEY (`institution`)
    REFERENCES `colab_db`.`institution` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`coach` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `principal` INT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT '0',
  `num_of_reports` INT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `coach_principal` (`principal` ASC) VISIBLE,
  CONSTRAINT `coach_principal`
    FOREIGN KEY (`principal`)
    REFERENCES `colab_db`.`principal` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`class` (
  `id` INT NOT NULL,
  `teacher` INT NOT NULL,
  `students` INT NULL DEFAULT NULL,
  `contents` VARCHAR(45) NULL DEFAULT NULL,
  `topic` VARCHAR(45) NULL DEFAULT NULL,
  `course` INT NULL DEFAULT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `class_teacher_idx` (`teacher` ASC) VISIBLE,
  INDEX `coach_creator_idx` (`created_by` ASC) VISIBLE,
  INDEX `class_course` (`course` ASC) VISIBLE,
  CONSTRAINT `class_course`
    FOREIGN KEY (`course`)
    REFERENCES `colab_db`.`course` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `class_teacher`
    FOREIGN KEY (`teacher`)
    REFERENCES `colab_db`.`teacher` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `coach_creator`
    FOREIGN KEY (`created_by`)
    REFERENCES `colab_db`.`coach` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`map` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `num_classes` INT NULL DEFAULT NULL,
  `institution` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `map_institution` (`institution` ASC) VISIBLE,
  CONSTRAINT `map_institution`
    FOREIGN KEY (`institution`)
    REFERENCES `colab_db`.`institution` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`class_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`class_locations` (
  `id` INT NOT NULL,
  `map` INT NULL DEFAULT NULL,
  `roomnumber` INT NULL DEFAULT NULL,
  `building` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `class_map` (`map` ASC) VISIBLE,
  CONSTRAINT `class_loc`
    FOREIGN KEY (`id`)
    REFERENCES `colab_db`.`class` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `class_map`
    FOREIGN KEY (`map`)
    REFERENCES `colab_db`.`map` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`counselor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`counselor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `num_of_reports` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`report` (
  `id` INT NOT NULL,
  `counselor` INT NULL DEFAULT NULL,
  `report_details` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `report_counselor` (`counselor` ASC) VISIBLE,
  CONSTRAINT `report_counselor`
    FOREIGN KEY (`counselor`)
    REFERENCES `colab_db`.`counselor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`coach_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`coach_report` (
  `id` INT NOT NULL,
  `contents` VARCHAR(45) NULL DEFAULT NULL,
  `rating` FLOAT NULL DEFAULT NULL,
  `report` INT NOT NULL,
  PRIMARY KEY (`id`, `report`),
  INDEX `report_c_id_idx` (`report` ASC) VISIBLE,
  CONSTRAINT `coach`
    FOREIGN KEY (`id`)
    REFERENCES `colab_db`.`coach` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `report_c_id`
    FOREIGN KEY (`report`)
    REFERENCES `colab_db`.`report` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`lesson` (
  `id` INT NOT NULL,
  `course` INT NULL DEFAULT NULL,
  `lesson_title` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `lesson_course` (`course` ASC) VISIBLE,
  CONSTRAINT `lesson_course`
    FOREIGN KEY (`course`)
    REFERENCES `colab_db`.`course` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`module` (
  `id` INT NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `contents` VARCHAR(45) NULL DEFAULT NULL,
  `lesson` INT NULL DEFAULT NULL,
  `course` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `lesson_module` (`lesson` ASC) VISIBLE,
  INDEX `module_course` (`course` ASC) VISIBLE,
  CONSTRAINT `lesson_module`
    FOREIGN KEY (`lesson`)
    REFERENCES `colab_db`.`lesson` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `module_course`
    FOREIGN KEY (`course`)
    REFERENCES `colab_db`.`course` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`homework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`homework` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `grade` INT NULL DEFAULT NULL,
  `module` INT NULL DEFAULT NULL,
  `student` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `module_homework_idx` (`module` ASC) VISIBLE,
  INDEX `student_homework` (`student` ASC) VISIBLE,
  CONSTRAINT `module_homework`
    FOREIGN KEY (`module`)
    REFERENCES `colab_db`.`module` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `student_homework`
    FOREIGN KEY (`student`)
    REFERENCES `colab_db`.`student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`student_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`student_report` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `report_contents` VARCHAR(45) NULL DEFAULT NULL,
  `report` INT NOT NULL,
  PRIMARY KEY (`id`, `report`),
  INDEX `student_report_idx` (`report` ASC) VISIBLE,
  CONSTRAINT `student`
    FOREIGN KEY (`id`)
    REFERENCES `colab_db`.`student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_report`
    FOREIGN KEY (`report`)
    REFERENCES `colab_db`.`report` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`students` (
  `id` INT NOT NULL,
  `student` INT NOT NULL,
  `class` INT NOT NULL,
  `attendance` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`student`, `class`),
  INDEX `student_in_class_idx` (`student` ASC) VISIBLE,
  INDEX `students_class_idx` (`class` ASC) VISIBLE,
  CONSTRAINT `student_in_class`
    FOREIGN KEY (`student`)
    REFERENCES `colab_db`.`student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `students_class`
    FOREIGN KEY (`class`)
    REFERENCES `colab_db`.`class` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`teacher_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`teacher_report` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `course` VARCHAR(45) NULL DEFAULT NULL,
  `number_of_courses` INT NULL DEFAULT NULL,
  `report` INT NOT NULL,
  PRIMARY KEY (`id`, `report`),
  INDEX `teacher_report_idx` (`report` ASC) VISIBLE,
  CONSTRAINT `teacher`
    FOREIGN KEY (`id`)
    REFERENCES `colab_db`.`teacher` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teacher_report`
    FOREIGN KEY (`report`)
    REFERENCES `colab_db`.`report` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`test` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `module` INT NULL DEFAULT NULL,
  `student` INT NULL DEFAULT NULL,
  `grade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `module_test_idx` (`module` ASC) VISIBLE,
  INDEX `student_test` (`student` ASC) VISIBLE,
  CONSTRAINT `module_test`
    FOREIGN KEY (`module`)
    REFERENCES `colab_db`.`module` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `student_test`
    FOREIGN KEY (`student`)
    REFERENCES `colab_db`.`student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `colab_db`.`tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colab_db`.`tutors` (
  `id` INT NOT NULL,
  `sessions` INT NULL DEFAULT NULL,
  `topic` VARCHAR(45) NULL DEFAULT NULL,
  `student` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `student_idx` (`student` ASC) VISIBLE,
  INDEX `student_tutored_idx` (`student` ASC) VISIBLE,
  CONSTRAINT `student_tutor`
    FOREIGN KEY (`id`)
    REFERENCES `colab_db`.`student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_tutored`
    FOREIGN KEY (`student`)
    REFERENCES `colab_db`.`student` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
